import {
  cilWallet,
  cilCalendarCheck,
  cilWindowMaximize,
  cilHandPointDown,
  cilInstitution,
  cilWrapText,
  cilFlightTakeoff,
  cilInfinity,
  cilScreenSmartphone,
  cibAllocine,
  cibGmail,
  cilFlip,
  cilFingerprint,
  cilDataTransferDown,
  cilHamburgerMenu,
  cilBriefcase,
  cilMediaSkipForward,
  cilMediaSkipBackward,
  cilScreenDesktop,
  cilHistory,
  cilDescription,
  cilDiamond,
  cilHeader,
  cilGlobeAlt,
  cilLibraryBuilding,
  cilInfo,
  cilArrowCircleLeft,
  cilCheckCircle,
  cilCircle,
  cilFlagAlt,
  cilCheckAlt,
  cilArrowThickBottom,
  cilVerticalAlignBottom,
  cilXCircle,
  cilWarning,
  cilArrowLeft,
  cilSearch,
  cibFacebookF,
  cibYoutube,
  cilTouchApp,
  cilLightbulb,
  cilCloudUpload,
  cilFolder,
  cilPlaylistAdd,
  cilAirplay,
  cilGroup,
  cilContact,
  cilColorBorder,
  cilEnvelopeLetter,
  cilSend,
  cilPenAlt,
  cilSync,
  cilChevronDoubleRight,
  cilInput,
  cilLockUnlocked,
  cilReload,
  cilExitToApp,
  cilClipboard,
  cilPowerStandby,
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cilArrowThickRight,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilArrowCircleRight,
  cilBank,
  cilBan,
  cilBasket,
  cilBasketball,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoney,
  cilMoon,
  cilNotes,
  cilOptions,
  cilOpacity,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilTransfer,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilClearAll,
  cilPlus,
  cilMinus,
  cilWindowMinimize,
  cilChatBubble,
  cilListLowPriority,
  cilLineStyle,
  cilBook,
  cilCart,
} from '@coreui/icons';

export const iconSubset = {
  cilWallet,
  cilCalendarCheck,
  cilWindowMaximize,
  cilHandPointDown,
  cilInstitution,
  cilWrapText,
  cilFlightTakeoff,
  cilInfinity,
  cilScreenSmartphone,
  cibAllocine,
  cibGmail,
  cilFlip,
  cilFingerprint,
  cilDataTransferDown,
  cilHamburgerMenu,
  cilBriefcase,
  cilMediaSkipForward,
  cilMediaSkipBackward,
  cilHistory,
  cilDescription,
  cilDiamond,
  cilHeader,
  cilGlobeAlt,
  cilLibraryBuilding,
  cilInfo,
  cilArrowCircleLeft,
  cilCheckCircle,
  cilCircle,
  cilFlagAlt,
  cilCheckAlt,
  cilArrowThickBottom,
  cilVerticalAlignBottom,
  cilWarning,
  cilXCircle,
  cilArrowLeft,
  cilSearch,
  cibFacebookF,
  cibYoutube,
  cilTouchApp,
  cilLightbulb,
  cilCloudUpload,
  cilFolder,
  cilPlaylistAdd,
  cilAirplay,
  cilGroup,
  cilContact,
  cilColorBorder,
  cilEnvelopeLetter,
  cilSend,
  cilPenAlt,
  cilSync,
  cilChevronDoubleRight,
  cilInput,
  cilLockUnlocked,
  cilReload,
  cilExitToApp,
  cilClipboard,
  cilPowerStandby,
  cibCcAmex,
  cilArrowThickRight,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAlignCenter,
  cilAccountLogout,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilArrowCircleRight,
  cilBank,
  cilBan,
  cilBasket,
  cilBasketball,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoney,
  cilMoon,
  cilNotes,
  cilOptions,
  cilOpacity,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilTransfer,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilClearAll,
  cilPlus,
  cilMinus,
  cilWindowMinimize,
  cilChatBubble,
  cilListLowPriority,
  cilLineStyle,
  cilBook,
  cilScreenDesktop,
  cilCart,
};

export enum IconSubset {
  cilWallet = 'cilWallet',
  cilCalendarCheck = 'cilCalendarCheck',
  cilWindowMaximize = 'cilWindowMaximize',
  cilHandPointDown = 'cilHandPointDown',
  cilInstitution = 'cilInstitution',
  cilWrapText = 'cilWrapText',
  cilFlightTakeoff = 'cilFlightTakeoff',
  cilInfinity = 'cilInfinity',
  cilScreenSmartphone = 'cilScreenSmartphone',
  cibAllocine = 'cibAllocine',
  cibGmail = 'cibGmail',
  cilFlip = 'cilFlip',
  cilFingerprint = 'cilFingerprint',
  cilHamburgerMenu = 'cilHamburgerMenu',
  cilDataTransferDown ='cilDataTransferDown',
  cilBriefcase ='cilBriefcase',
  cilMediaSkipForward = 'cilMediaSkipForward',
  cilMediaSkipBackward = 'cilMediaSkipBackward',
  cilScreenDesktop = 'cilScreenDesktop',
  cilHistory = 'cilHistory',
  cilDescription = 'cilDescription',
  cilDiamond = 'cilDiamond',
  cilHeader = 'cilHeader',
  cilGlobeAlt = 'cilGlobeAlt',
  cilLibraryBuilding = 'cilLibraryBuilding',
  cilInfo = 'cilInfo',
  cilArrowCircleLeft = 'cilArrowCircleLeft,',
  cilCheckCircle = 'cilCheckCircle',
  cilCircle = 'cilCircle',
  cilFlagAlt = 'cilFlagAlt',
  cilCheckAlt = 'cilCheckAlt',
  cilArrowThickBottom = 'cilArrowThickBottom',
  cilVerticalAlignBottom = 'cilVerticalAlignBottom',
  cilWarning = 'cilWarning',
  cilXCircle = 'cilXCircle',
  cilArrowLeft = 'cilArrowLeft',
  cilSearch = 'cilSearch',
  cibFacebookF = 'cibFacebookF',
  cibYoutube = 'cibYoutube',
  cilTouchApp = 'cilTouchApp',
  cilLightbulb = 'cilLightbulb',
  cilCloudUpload = 'cilCloudUpload',
  cilFolder = 'cilFolder',
  cilPlaylistAdd = 'cilPlaylistAdd',
  cilAirplay = 'cilAirplay',
  cilGroup = 'cilGroup',
  cilContact = 'cilContact',
  cilColorBorder = 'cilColorBorder',
  cilEnvelopeLetter = 'cilEnvelopeLetter',
  cilSend = 'cilSend',
  cilPenAlt = 'cilPenAlt',
  cilSync = 'cilSync',
  cilChevronDoubleRight = 'cilChevronDoubleRight',
  cilInput = 'cilInput',
  cilLockUnlocked = 'cilLockUnlocked',
  cilReload = 'cilReload',
  cilExitToApp = 'cilExitToApp',
  cilPowerStandby = 'cilPowerStandby',
  cilClipboard = 'cilClipboard',
  cibCcAmex = 'cibCcAmex',
  cibCcApplePay = 'cibCcApplePay',
  cibCcMastercard = 'cibCcMastercard',
  cibCcPaypal = 'cibCcPaypal',
  cibCcStripe = 'cibCcStripe',
  cibCcVisa = 'cibCcVisa',
  cibFacebook = 'cibFacebook',
  cibGoogle = 'cibGoogle',
  cibLinkedin = 'cibLinkedin',
  cibSkype = 'cibSkype',
  cibTwitter = 'cibTwitter',
  cifBr = 'cifBr',
  cifEs = 'cifEs',
  cifFr = 'cifFr',
  cifIn = 'cifIn',
  cifPl = 'cifPl',
  cifUs = 'cifUs',
  cilAlignCenter = 'cilAlignCenter',
  cilAccountLogout = 'cilAccountLogout',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilArrowCircleRight = 'cilArrowCircleRight',
  cilBank = 'cilBank',
  cilBan = 'cilBan',
  cilBasket = 'cilBasket',
  cilBasketball = 'cilBasketball',
  cilBell = 'cilBell',
  cilBold = 'cilBold',
  cilArrowThickRight = 'cilArrowThickRight',
  cilBookmark = 'cilBookmark',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck='cilCheck',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCommentSquare = 'cilCommentSquare',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilFile = 'cilFile',
  cilHome = 'cilHome',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilLanguage = 'cilLanguage',
  cilLayers = 'cilLayers',
  cilList = 'cilList',
  cilListNumbered = 'cilListNumbered',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaPlay = 'cilMediaPlay',
  cilMenu = 'cilMenu',
  cilMoney = 'cilMoney',
  cilMoon = 'cilMoon',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilOpacity = 'cilOpacity',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPrint = 'cilPrint',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareBoxed = 'cilShareBoxed',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilSun = 'cilSun',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTrash = 'cilTrash',
  cilTransfer = 'cilTransfer',
  cilUnderline = 'cilUnderline',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
  cilClearAll = 'cilClearAll',
  cilPlus = 'cilPlus',
  cilMinus = 'cilMinus',
  cilWindowMinimize = 'cilWindowMinimize',
  cilChatBubble = 'cilChatBubble',
  cilListLowPriority = 'cilListLowPriority',
  cilLineStyle = 'cilLineStyle',
  cilBook = 'cilBook',
  cilCart ='cilCart',
}
